dist: xenial

language: node_js

node_js:
  - "8"

stages:
  - lint
  - deploy

git:
  depth: 1

jobs:
  include:
    - stage: lint
      name: EditorConfig Syntax Verification
      install:
        - npm install -g eclint
        - eclint --version
      script: eclint check
    - stage: lint
      name: Shell Script Syntax Verification
      script: make sh/lint
    - stage: lint
      name: JSON Lint/Format Verification
      script: make json/lint
    - stage: lint
      name: Salt Lint Verification
      install: make salt-lint/install
      script: make salt/lint
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/pwm-formula
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [pwm-formula v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/pwm-formula/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure:
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/pwm-formula
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'

